export { deriveActivityTiming } from './activities/timing'
export {
  ACTIVITY_APPLE_REWARDS,
  BASE_ACTIVITY_DURATION_MINUTES,
  BASE_ACTIVITY_DURATION_MS,
  DEFAULT_POMODORO_DURATION_MS,
  DUPLICATE_APPLE_COMPENSATION,
  FRIEND_IDS,
  INITIAL_APPLES,
  INITIAL_INVENTORY,
  ITEM_IDS,
  LEGACY_ITEM_IDS,
  ITEM_PRICES,
  PIANO_NOTE_IDS,
  LEGACY_ACTIVITY_DURATION_MS,
  MAX_COMPANION_DAYS,
  MAX_POMODORO_DURATION_MS,
  MIN_POMODORO_DURATION_MS,
  REALITY_REWARD_INTERVAL_MS,
  VITALITY_MAGIC_COMPANION_DAYS,
  PET_ENCOURAGEMENT_APPLE_COST,
  PITY_THRESHOLDS,
} from './game/constants'
export {
  COLLECTION_DROP_CHANCES,
  createDefaultGameBalance,
  DEFAULT_GAME_BALANCE,
  DEFAULT_GAME_BALANCE_V2,
  DEFAULT_GAME_BALANCE_V3,
  addProbabilityBonus,
  APPLE_LUNCHBOX_FRIEND_BONUS,
  createDefaultGameBalanceV2,
  createDefaultGameBalanceV3,
  FRIEND_GIFT_APPLES_BY_ID,
  FRIEND_GIFT_ITEM_BY_ID,
  FRIEND_EVENT_CHANCE,
  isValidActivityDuration,
  isValidProbability,
  LUCKY_APPLE_COLLECTION_DROP_BONUS,
  PROBABILITY_KEYS,
  REST_COMPLETION_APPLES,
  type GameBalance,
  type GameBalanceV2,
  type GameBalanceV3,
  type GameProbabilities,
  type ProbabilityKey,
} from './game/gameBalance'
export { createInitialGameState, type InitialGameOptions } from './game/createGameState'
export { assertValidTimestamp, isValidTimestamp, MAX_DATE_TIMESTAMP_MS } from './game/time'
export { incrementSafeCounter, saturatingAddSafeCounter } from './game/counters'
export {
  gameStateV1Schema,
  isStrictGameStateV1,
  migrateGameStateV1,
  migrateGameStateV1ToV2,
  type MigrateGameStateV1Options,
} from './game/migrateGameStateV1'
export {
  gameStateV2Schema,
  isStrictGameStateV2,
  migrateGameStateV1ToV3,
  migrateGameStateV2ToV3,
  migrateStoredGameStateToV3,
  type MigrateGameStateV2Options,
  type StoredGameStateThroughV3,
} from './game/migrateGameStateV2'
export {
  gameStateV3Schema,
  gameStateV4Schema,
  isStrictGameStateV3,
  isStrictGameStateV4,
  migrateGameStateV1ToV4,
  migrateGameStateV2ToV4,
  migrateGameStateV3ToV4,
  migrateStoredGameStateToV4,
  type MigrateGameStateV3Options,
  type StoredGameState,
} from './game/migrateGameStateV3'
export { reduceGame } from './game/reducer'
export {
  isProductivityAction,
  reduceProductivity,
  type ProductivityAction,
} from './game/productivity'
export { normalizeImportedGameBalance } from './game/normalizeImportedGameBalance'
export {
  isValidDisplayName,
  MAX_DISPLAY_NAME_LENGTH,
  MIN_DISPLAY_NAME_LENGTH,
  normalizeDisplayName,
} from './game/profile'
export { reconcileGameStateWithCatalog } from './game/reconcileGameStateWithCatalog'
export {
  validateImportedGameState,
  type ImportedGameStateValidation,
  type ImportedGameStateValidationCode,
} from './game/validateImportedGameState'
export {
  validateCollectionCatalog,
  type CollectionCatalogValidation,
} from './game/validateCollectionCatalog'
export type {
  ActivityKind,
  ActivityPhase,
  ActivityPreferences,
  ActivityRun,
  ActivityRunV2,
  ActivityTiming,
  ClaimSummary,
  CollectionCatalog,
  CollectionEntry,
  CollectibleCategory,
  CollectibleActivityKind,
  FriendCollection,
  FriendEntry,
  FriendId,
  GameAction,
  GameEffect,
  GameError,
  GameErrorCode,
  GameState,
  GameStateV1,
  GameStateV2,
  GameStateV3,
  GameStateV4,
  GameTransition,
  Inventory,
  ItemId,
  LegacyInventory,
  LegacyItemId,
  LegacyActivityKind,
  PetLocation,
  PetLocationV3,
  PetInterest,
  PetState,
  PityState,
  RewardPlan,
  RewardPlanV2,
  RoomArea,
  LegacyRoomArea,
  MusicLoopMode,
  MusicPlayerState,
  MusicPlaylist,
  PianoNoteId,
  PlayerState,
  PomodoroSession,
  PomodoroState,
  RealityRewardDecision,
  RealitySettlement,
  RealityState,
  RealityStay,
  TodoItem,
  VitalityEffect,
  WorldDimension,
  TaskBoard,
  TaskEvent,
  TaskId,
  TaskInstance,
  TaskTriggerGroup,
} from './game/types'
export {
  ALL_ACTIVITY_PREFERENCES,
  getVitalityMagicAvailability,
  isVitalityActive,
  resolveVitalityForCompanionDayAdvance,
  vitalityExpiryDay,
  type CompanionDayVitalityResolution,
  type VitalityMagicAvailability,
  type VitalityMagicUnavailableReason,
} from './player/vitality'
export {
  exhaustActivityPreference,
  generateActivityPreferences,
  getRefusalCountForRoll,
  interestForActivity,
  isPetTired,
  type GeneratedPreferences,
} from './pet/preferences'
export { createRandomCursor, hashSeed, nextRandom, randomInteger } from './rewards/prng'
export { planActivityReward, type RewardPlanningInput } from './rewards/planReward'
export {
  canUseLuckyApple,
  getLuckyAppleAvailability,
  type LuckyAppleAvailability,
} from './rewards/luckyApple'
export {
  applyTaskEvent,
  generateTaskBoard,
  getTaskPresentation,
  getTaskProgressLabel,
  isTaskCompleted,
  hasRetiredTask,
  replaceRetiredTaskBoard,
  TASK_LIBRARY,
  validateTaskInstanceReachability,
  type GeneratedTaskBoard,
  type TaskReachabilityValidation,
  type TaskPresentation,
  type TaskTemplate,
  type ReplaceRetiredTaskBoardInput,
} from './tasks/taskBoard'
