export { deriveActivityTiming } from './activities/timing'
export {
  ACTIVITY_APPLE_REWARDS,
  BASE_ACTIVITY_DURATION_MINUTES,
  BASE_ACTIVITY_DURATION_MS,
  BILIBILI_BVID_PATTERN,
  DEFAULT_STREAM_FAVORITE_ID,
  DEFAULT_POMODORO_BREAK_DURATION_MS,
  DEFAULT_POMODORO_DURATION_MS,
  DUPLICATE_APPLE_COMPENSATION,
  FRIEND_IDS,
  INITIAL_APPLES,
  INITIAL_INVENTORY,
  ITEM_IDS,
  LEGACY_ITEM_IDS,
  ITEM_PRICES,
  PIANO_NOTE_IDS,
  POMODORO_PRESETS,
  LEGACY_ACTIVITY_DURATION_MS,
  MAX_COMPANION_DAYS,
  MAX_POMODORO_DURATION_MS,
  MIN_POMODORO_DURATION_MS,
  REALITY_REWARD_INTERVAL_MS,
  STREAM_FAVORITE_IDS,
  VITALITY_MAGIC_COMPANION_DAYS,
  PET_ENCOURAGEMENT_APPLE_COST,
  PITY_THRESHOLDS,
  type PomodoroPreset,
} from './game/constants'
export {
  COLLECTION_DROP_CHANCES,
  createDefaultGameBalance,
  DEFAULT_GAME_BALANCE,
  DEFAULT_GAME_BALANCE_V2,
  DEFAULT_GAME_BALANCE_V3,
  addNonStackingBaseProbabilityBonus,
  APPLE_LUNCHBOX_FRIEND_BASE_BONUS_RATE,
  createDefaultGameBalanceV2,
  createDefaultGameBalanceV3,
  FRIEND_GIFT_APPLES_BY_ID,
  FRIEND_GIFT_ITEM_BY_ID,
  FRIEND_EVENT_CHANCE,
  isValidActivityDuration,
  isValidProbability,
  LEGACY_FRIEND_GIFT_APPLES_BY_ID,
  LUCKY_APPLE_COLLECTION_BASE_BONUS_RATE,
  multiplyProbability,
  PROBABILITY_KEYS,
  REST_COMPLETION_APPLES,
  TRAVEL_FRIEND_GIFT_APPLES_BY_ID,
  type GameBalance,
  type GameBalanceV2,
  type GameBalanceV3,
  type GameProbabilities,
  type ProbabilityKey,
} from './game/gameBalance'
export { createInitialGameState, type InitialGameOptions } from './game/createGameState'
export { assertValidTimestamp, isValidTimestamp, MAX_DATE_TIMESTAMP_MS } from './game/time'
export { incrementSafeCounter, saturatingAddSafeCounter } from './game/counters'
export {
  gameStateV1Schema,
  isStrictGameStateV1,
  migrateGameStateV1,
  migrateGameStateV1ToV2,
  type MigrateGameStateV1Options,
} from './game/migrateGameStateV1'
export {
  gameStateV2Schema,
  isStrictGameStateV2,
  migrateGameStateV1ToV3,
  migrateGameStateV2ToV3,
  migrateStoredGameStateToV3,
  type MigrateGameStateV2Options,
  type StoredGameStateThroughV3,
} from './game/migrateGameStateV2'
export {
  gameStateV3Schema,
  gameStateV4Schema,
  isStrictGameStateV3,
  isStrictGameStateV4,
  migrateGameStateV1ToV4,
  migrateGameStateV2ToV4,
  migrateGameStateV3ToV4,
  migrateStoredGameStateToV4,
  type MigrateGameStateV3Options,
  type StoredGameStateThroughV4,
} from './game/migrateGameStateV3'
export {
  gameStateV5LegacyMusicSchema,
  gameStateV5Schema,
  isStrictGameStateV5,
  migrateGameStateV4ToV5,
  migrateStoredGameStateToV5,
  type StoredGameStateThroughV5,
} from './game/migrateGameStateV4'
export {
  gameStateV6Schema,
  isStrictGameStateV6,
  migrateGameStateV5ToV6,
  migrateStoredGameStateToV6,
  type StoredGameStateThroughV6,
} from './game/migrateGameStateV5'
export {
  gameStateV7Schema,
  isStrictGameStateV7,
  migrateGameStateV6ToV7,
  migrateStoredGameStateToV7,
  type StoredGameStateThroughV7,
} from './game/migrateGameStateV6'
export {
  gameStateV8Schema,
  isStrictGameStateV8,
  migrateGameStateV7ToV8,
  migrateStoredGameStateToV8,
} from './game/migrateGameStateV7'
export {
  gameStateV9Schema,
  isStrictGameStateV9,
  migrateGameStateV8ToV9,
  migrateStoredGameStateToV9,
} from './game/migrateGameStateV8'
export {
  gameStateV10Schema,
  isStrictGameStateV10,
  migrateGameStateV9ToV10,
  migrateStoredGameStateToV10,
  type StoredGameState as StoredGameStateThroughV10,
} from './game/migrateGameStateV9'
export {
  gameStateV11Schema,
  isStrictGameStateV11,
  migrateGameStateV10ToV11,
  migrateStoredGameStateToV11,
  WARDROBE_LAYOUT_VERSION_V11,
  type StoredGameState as StoredGameStateThroughV11,
  wardrobeStateSchema,
  wardrobeTransformSchema,
} from './game/migrateGameStateV10'
export {
  gameStateV12Schema,
  isStrictGameStateV12,
  migrateGameStateV11ToV12,
  migrateStoredGameStateToV12,
  type StoredGameState,
  wardrobeStateV12Schema,
  wardrobeTransformV12Schema,
} from './game/migrateGameStateV11'
export { reduceGame } from './game/reducer'
export {
  isStreamDailyRewardAction,
  isValidLocalDateKey,
  reduceStreamDailyReward,
  STREAM_DAILY_REWARD_APPLES,
  type StreamDailyRewardAction,
} from './game/streamDailyReward'
export {
  createInitialWardrobeState,
  generateWardrobeShop,
  getAvailableWardrobeTargets,
  getOwnedWardrobeItems,
  getSavedWardrobeLooks,
  getWardrobeLook,
  getWardrobeCatalogItem,
  getWardrobePhotos,
  getWardrobePhotoLayers,
  getWardrobePurchaseAvailability,
  getWardrobeShopItems,
  isValidWardrobeTransform,
  isValidWardrobeElementTransform,
  isWardrobeAction,
  isWardrobeAssetId,
  isWardrobeTargetAvailable,
  MAX_WARDROBE_LOOK_ELEMENTS,
  MAX_WARDROBE_LOOK_NAME_LENGTH,
  MAX_WARDROBE_LOOKS_PER_TARGET,
  MAX_WARDROBE_PHOTOS,
  MAX_WARDROBE_PHOTO_PARTICIPANTS,
  MAX_WARDROBE_PHOTO_DECORATIONS,
  reduceWardrobe,
  refreshWardrobeShopForCompanionDay,
  STARTER_WARDROBE_ASSET_IDS,
  WARDROBE_ASSET_IDS,
  WARDROBE_CATALOG,
  WARDROBE_LAYOUT_VERSION,
  WARDROBE_SHOP_SIZE,
  type WardrobeAction,
  type WardrobePurchaseAvailability,
} from './game/wardrobe'
export {
  deriveRealityActiveDurationMs,
  isProductivityAction,
  reduceProductivity,
  suspendRealityLeaseAfterLoad,
  type ProductivityAction,
} from './game/productivity'
export { normalizeImportedGameBalance } from './game/normalizeImportedGameBalance'
export {
  isValidDisplayName,
  MAX_DISPLAY_NAME_LENGTH,
  MIN_DISPLAY_NAME_LENGTH,
  normalizeDisplayName,
} from './game/profile'
export { reconcileGameStateWithCatalog } from './game/reconcileGameStateWithCatalog'
export {
  validateImportedGameState,
  type ImportedGameStateValidation,
  type ImportedGameStateValidationCode,
} from './game/validateImportedGameState'
export {
  validateCollectionCatalog,
  type CollectionCatalogValidation,
} from './game/validateCollectionCatalog'
export type {
  ActivityKind,
  ActivityPhase,
  ActivityPreferences,
  ActivityRun,
  ActivityRunV2,
  ActivityTiming,
  ClaimSummary,
  CollectionCatalog,
  CollectionEntry,
  CollectibleCategory,
  CollectibleActivityKind,
  FriendCollection,
  FriendEntry,
  FriendId,
  GameAction,
  GameEffect,
  GameError,
  GameErrorCode,
  GameState,
  GameStateV1,
  GameStateV2,
  GameStateV3,
  GameStateV4,
  GameStateV5,
  GameStateV5LegacyMusic,
  GameStateV6,
  GameStateV7,
  GameStateV8,
  GameStateV9,
  GameStateV10,
  GameStateV11,
  GameStateV12,
  GameTransition,
  Inventory,
  ItemId,
  LegacyInventory,
  LegacyItemId,
  LegacyActivityKind,
  PetLocation,
  PetLocationV3,
  PetInterest,
  PetState,
  PityState,
  RewardPlan,
  RewardPlanV2,
  RoomArea,
  LegacyRoomArea,
  MusicLoopMode,
  MusicPlayerState,
  PianoNoteId,
  PlayerState,
  StreamSettings,
  StreamSettingsV8,
  StreamFavoriteId,
  PomodoroBackgroundRef,
  PomodoroSession,
  PomodoroSessionV12,
  PomodoroSessionV4,
  PomodoroState,
  PomodoroStateV12,
  PomodoroStateV4,
  RealityRewardDecision,
  RealitySettlement,
  RealitySettlementV8,
  RealityState,
  RealityStateV4,
  RealityStateV6,
  RealityStateV7,
  RealityStateV8,
  RealityStateV9,
  RealityStateV10,
  RealityStateV12,
  RealityStay,
  RealityStayV8,
  StreamHistory,
  StreamHistoryV6,
  StreamRoundRecord,
  StreamSessionOutcome,
  StreamSessionRecord,
  StreamDailyRewardState,
  TodoItem,
  VitalityEffect,
  WardrobeAssetCategory,
  WardrobeAssetId,
  WardrobeCatalogItem,
  WardrobeElement,
  WardrobeElementTransform,
  WardrobeElementV11,
  WardrobePhoto,
  WardrobePhotoDecoration,
  WardrobePhotoLayer,
  WardrobePhotoParticipant,
  WardrobePhotoParticipantV11,
  WardrobePhotoV11,
  WardrobeState,
  WardrobeStateV11,
  WardrobeTargetId,
  WardrobeTransform,
  WardrobeTransformV11,
  SavedWardrobeLook,
  SavedWardrobeLookV11,
  WorldDimension,
  TaskBoard,
  TaskBoardV4,
  TaskEvent,
  TaskId,
  TaskInstance,
  TaskTriggerGroup,
} from './game/types'
export {
  ALL_ACTIVITY_PREFERENCES,
  getVitalityMagicAvailability,
  isVitalityActive,
  resolveVitalityForCompanionDayAdvance,
  vitalityExpiryDay,
  type CompanionDayVitalityResolution,
  type VitalityMagicAvailability,
  type VitalityMagicUnavailableReason,
} from './player/vitality'
export {
  exhaustActivityPreference,
  generateActivityPreferences,
  getPetVitalityStatus,
  getRefusalCountForRoll,
  interestForActivity,
  isPetTired,
  type GeneratedPreferences,
  type PetVitalityStatus,
} from './pet/preferences'
export { createRandomCursor, hashSeed, nextRandom, randomInteger } from './rewards/prng'
export { planActivityReward, type RewardPlanningInput } from './rewards/planReward'
export {
  canUseLuckyApple,
  getLuckyAppleAvailability,
  type LuckyAppleAvailability,
} from './rewards/luckyApple'
export {
  applyTaskEvent,
  generateTaskBoard,
  getAssignableTaskIds,
  getTaskPresentation,
  getTaskProgressLabel,
  isTaskCompleted,
  hasRetiredTask,
  meetsTaskAssignmentRequirements,
  meetsTaskInstanceAssignmentRequirements,
  MAX_TASK_TEMPLATE_REWARD_APPLES,
  reconcileTaskBoardAvailability,
  replaceRetiredTaskBoard,
  TASK_LIBRARY,
  validateTaskInstanceReachability,
  type GeneratedTaskBoard,
  type ReconciledTaskBoard,
  type ReconcileTaskBoardAvailabilityInput,
  type TaskAssignmentRequirement,
  type TaskAvailabilityInput,
  type TaskReachabilityValidation,
  type TaskPresentation,
  type TaskTemplate,
  type TaskTemplateRewardApples,
  type ReplaceRetiredTaskBoardInput,
} from './tasks/taskBoard'
